// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Domain.Entities.Coin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Circulating_supply")
                        .HasColumnType("double");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Current_price")
                        .HasColumnType("double");

                    b.Property<double>("High_24h")
                        .HasColumnType("double");

                    b.Property<DateTime>("Last_updated")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Low_24h")
                        .HasColumnType("double");

                    b.Property<double>("Market_cap")
                        .HasColumnType("double");

                    b.Property<double>("Market_cap_change_24h")
                        .HasColumnType("double");

                    b.Property<double>("Market_cap_change_percentage_24h")
                        .HasColumnType("double");

                    b.Property<double>("Market_cap_rank")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price_change_24h")
                        .HasColumnType("double");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.Property<double>("Total_volume")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
